[#823] Model build operator
legion-platform/legion-infrastructure pull request #3
Opened 2019-04-10 09:39 UTC by mcdoker18

* Removed deploy of core legioni helm chart
* Removed creation of jenkins aws resources

2019-04-15 08:40 UTC, alexander-semenets commented
- https://github.com/legion-platform/legion-aws/blob/3bb5836159e19d646812b426ca3bb9aa8eea5a2e/ansible/vars/common.yaml#L31 
this var is not needed anymore I guess

Unused parameters (+ respective jobs) ?
https://github.com/legion-platform/legion-aws/blob/3bb5836159e19d646812b426ca3bb9aa8eea5a2e/pipelines/build-and-deploy-legion.Jenkinsfile#L10
https://github.com/legion-platform/legion-aws/blob/3bb5836159e19d646812b426ca3bb9aa8eea5a2e/pipelines/ci-app.Jenkinsfile#L12

Unused var?
https://github.com/legion-platform/legion-aws/blob/0bc3890bfa7b31efa9ec4ac1e3d5eb572c110efd/pipelines/legionPipeline.groovy#L53

No need in jenkins plugin repo cleanup:
https://github.com/legion-platform/legion-aws/blob/3bb5836159e19d646812b426ca3bb9aa8eea5a2e/tools/cleanup_nexus_repo#L40

2019-04-15 08:56 UTC, alexander-semenets requested changes
pls see the comments in conversation

2019-04-16 05:53 UTC, alexander-semenets approved these changes

2019-04-16 12:13 UTC, kirillmakhonin approved these changes

2019-04-16 13:58 UTC, merged