[#9280 param store
legion-platform/legion-infrastructure pull request #30
Opened 2019-08-15 20:16 UTC by alexander-semenets

This fixes #928 issue. Must be merged together with appropriate PRs in legion and legion-profiles repos.
**REMINDER**: 
- GCP jobs must be updated according to temp _928 jobs after merge

2019-08-16 17:01 UTC, maxkochubey approved these changes

2019-08-16 17:26 UTC, kirillmakhonin approved these changes

2019-08-16 23:04 UTC, karbyshevds approved these changes

2019-08-19 08:27 UTC, mcdoker18 requested changes

2019-08-19 08:27 UTC, mcdoker18 commented on containers/kube-elb-security/README.md
> -It is useful if your services with Type `LoadBalancer` having firewall restrictions.
Rebase with the develop branch. Because we merged the deletion of kube elb deployment with the develop branch recently.

2019-08-19 08:27 UTC, mcdoker18 commented on pipelines/legionPipeline.groovy
> +                                extractHiera("json")
IMHO, it's a bad practice when our (legion\airflow\mlflow and so on) non-infra repositories know about hiera converter and its dependencies. For example, you install ruby, rubygems, hiera and pyyaml in the legion pipeline docker image https://github.com/legion-platform/legion/pull/970/files#diff-02048042aaff3c36726a71b3aa9a1fccR21 .
What do you think about the following way for robot tests?
```groovy
docker.image("infrasture-image") {
  extractHiera("json")
}
docker.image("legion-pipeline-agent") {
  run_robot_test()
}
```

2019-08-19 08:27 UTC, mcdoker18 commented on README.MD
>  CLUSTER_NAME=<CLUSTER_NAME_HERE> TF_DATA_DIR=/tmp/.terraform_${CLUSTER_NAME}_$(basename "$PWD") bash -c  'terraform init -backend-config="bucket=${CLUSTER_NAME}-tfstate"'
Can you provide mini documentation about usage of the hiera exporter? For example, I want to run robot tests or deploy legion infra locally. How can I generate a `profile.json` file?

2019-08-19 17:52 UTC, alexander-semenets commented on containers/kube-elb-security/README.md
> -It is useful if your services with Type `LoadBalancer` having firewall restrictions.
the container was removed

2019-08-19 18:02 UTC, mcdoker18 approved these changes

2019-08-20 18:30 UTC, merged