[#930] Pluggable build mechanism
legion-platform/legion-infrastructure pull request #39
Opened 2019-09-05 12:11 UTC by mcdoker18

* Added new legion-mlflow deployment
* Added Makefile(cluster creation/deletion, linters, export hiera script, build images and so on)
* Removed statsd exporter. Currently metrics are saved into mlflow service
* Added scripts to import hiera configuration in one step
* Replace nexus to google docker registry for model docker repository
* Added little doc about local development

2019-09-08 18:00 UTC, kirillmakhonin requested changes

2019-09-08 18:00 UTC, kirillmakhonin commented on terraform/modules/gcp/gke_cluster/main.tf
> +  version = "~> 2.12"
Why it is not exact version?

2019-09-08 18:00 UTC, kirillmakhonin commented on terraform/modules/legion/main.tf
> +data "aws_s3_bucket_object" "tls-secret-key" {
Do we use AWS even for GCP deployment for storing TLS certificates?

2019-09-08 18:00 UTC, kirillmakhonin commented on terraform/modules/legion/templates/mlflow.yaml
> +    domain: "mlflow.${cluster_name}.${root_domain}"
Why do we need .ingress.globalDomain with .tracking_server.ingress.domain? If we do not specify .tracking_server.ingress.domain template with .ingress.globalDomain should be used.

2019-09-08 18:00 UTC, kirillmakhonin commented on .gitwhitelisted
> +password: |
Looks like thing that is not secure (real password can be on a next line)

2019-09-08 18:36 UTC, mcdoker18 commented on terraform/modules/legion/main.tf
> +data "aws_s3_bucket_object" "tls-secret-key" {
Yes

2019-09-08 18:40 UTC, mcdoker18 commented on terraform/modules/gcp/gke_cluster/main.tf
> +  version = "~> 2.12"
I reverted this change.

2019-09-08 18:42 UTC, mcdoker18 commented on .gitwhitelisted
> +password: |
Provide an alternative

2019-09-08 21:08 UTC, mcdoker18 commented on terraform/modules/legion/templates/mlflow.yaml
> +    domain: "mlflow.${cluster_name}.${root_domain}"
Fixed

2019-09-08 22:17 UTC, kirillmakhonin commented on .gitwhitelisted
> +password: |
two-line regex?

2019-09-09 09:07 UTC, mcdoker18 commented on .gitwhitelisted
> +password: |
Can you provide an example?

2019-09-09 13:14 UTC, maxkochubey approved these changes

2019-09-10 08:35 UTC, alexander-semenets commented on terraform/modules/gcp/gke_cluster/variables.tf
> +variable "main_nodel_pool" {
mistype - nodel

2019-09-10 09:28 UTC, mcdoker18 commented on terraform/modules/gcp/gke_cluster/variables.tf
> +variable "main_nodel_pool" {
Fixed

2019-09-10 09:29 UTC, mcdoker18 commented on .gitwhitelisted
> +password: |
Sorry, but I do not understand how to fix this problem. If you provide an example, then I'll apply it.

2019-09-10 12:08 UTC, alexander-semenets approved these changes

2019-09-10 13:36 UTC, karbyshevds approved these changes

2019-09-10 13:37 UTC, alexander-semenets approved these changes

2019-09-11 04:17 UTC, merged