[#862] HELM refactoring
legion-platform/legion-infrastructure pull request #6
Opened 2019-04-23 14:57 UTC by kirillmakhonin

This closes #862 in legion repo.
This changes template for Legion HELM chart.
Should be merged with appropriate PR in Legion HELM chart (main repository)

2019-04-23 15:35 UTC, mcdoker18 requested changes

2019-04-23 15:35 UTC, mcdoker18 commented on ansible/roles/legion_enclave/templates/legion-values.yaml.j2
> +  buildPrefix: legion-ci
Remove hardcode

2019-04-24 15:30 UTC, kirillmakhonin commented on ansible/roles/legion_enclave/templates/legion-values.yaml.j2
> +  buildPrefix: legion-ci
done

2019-04-25 11:08 UTC, alexander-semenets approved these changes

2019-04-25 11:30 UTC, mcdoker18 approved these changes

2019-04-25 11:45 UTC, merged